export {Login} from "./auth/login/Login"
export {Home} from "./homepage/Home"
export {Allproducts} from "./products/allproducts/Allproducts"
export {Allusers} from "./users/allusers/Allusers"
export {UserDetails} from "./users/userDetails/UserDetails"